/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.AlumnoDAO;
import DAO.CursoDAO;
import DAO.GrupoDAO;
import Entities.Alumno;
import Entities.Curso;
import Entities.Grupo;
import Entities.Maestro;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jbran
 */
public class AdminGrupos extends javax.swing.JFrame {

    private Maestro usuario;
    private GrupoDAO grupos;
    private CursoDAO cursosDao;
    private AlumnoDAO alumnos;
    private Grupo seleccionado;
    private Alumno seleccionadoA;
    private List<Grupo> nuevos;

    /**
     * Creates new form AdminGrupos
     */
    public AdminGrupos(Maestro usuario) {
        initComponents();
        centrarPantalla();
        this.usuario = usuario;
        grupos = new GrupoDAO();
        cursosDao = new CursoDAO();
        alumnos = new AlumnoDAO();
        nuevos = new ArrayList<>();
        cargarComboBoxCursos();
        cargarGrupos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateTimePickerFechaHoraInicio = new com.github.lgooddatepicker.components.DateTimePicker();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnEliminarAlumno = new javax.swing.JButton();
        btnEditarAlumno = new javax.swing.JButton();
        btnAgregarAlumno = new javax.swing.JButton();
        txtNombreAlumno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cbxCursos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnConsultarAsistenciasNavegar = new javax.swing.JButton();
        btnAdminGruposNavegar = new javax.swing.JButton();
        btnImportAsistenciasNavegar = new javax.swing.JButton();
        btnAdminCursosNavegar = new javax.swing.JButton();
        btnAgregarGrupo = new javax.swing.JButton();
        btnEliminarGrupo = new javax.swing.JButton();
        btnEditarGrupo = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombreGrupo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(dateTimePickerFechaHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Alumnos"));

        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "IdGrupo"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        btnEliminarAlumno.setText("Eliminar Alumno");
        btnEliminarAlumno.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlumnoActionPerformed(evt);
            }
        });

        btnEditarAlumno.setText("Editar Alumno");
        btnEditarAlumno.setBackground(new java.awt.Color(255, 204, 102));
        btnEditarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAlumnoActionPerformed(evt);
            }
        });

        btnAgregarAlumno.setText("Agregar Alumno");
        btnAgregarAlumno.setBackground(new java.awt.Color(153, 255, 102));
        btnAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlumnoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre Alumno:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreAlumno)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, 970, 250));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupos"));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Curso", "FechaInicio"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setHeaderValue("FechaInicio");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 970, 230));

        cbxCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCursosActionPerformed(evt);
            }
        });
        getContentPane().add(cbxCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 140, 30));

        jLabel2.setText("Seleccione el curso:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        jLabel3.setText("Fecha y hora de inicio:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, 20));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Navegar"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConsultarAsistenciasNavegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calendar.png"))); // NOI18N
        btnConsultarAsistenciasNavegar.setText("Consultar asistencias");
        btnConsultarAsistenciasNavegar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnConsultarAsistenciasNavegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarAsistenciasNavegarActionPerformed(evt);
            }
        });
        jPanel2.add(btnConsultarAsistenciasNavegar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 170, 90));

        btnAdminGruposNavegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Windows_View_Detail.png"))); // NOI18N
        btnAdminGruposNavegar.setText("Administrar Grupos");
        btnAdminGruposNavegar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdminGruposNavegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminGruposNavegarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdminGruposNavegar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, 90));

        btnImportAsistenciasNavegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package.png"))); // NOI18N
        btnImportAsistenciasNavegar.setText("Importar asistencias");
        btnImportAsistenciasNavegar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnImportAsistenciasNavegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportAsistenciasNavegarActionPerformed(evt);
            }
        });
        jPanel2.add(btnImportAsistenciasNavegar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 170, 90));

        btnAdminCursosNavegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Windows_View_Detail.png"))); // NOI18N
        btnAdminCursosNavegar.setText("Administrar Cursos");
        btnAdminCursosNavegar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdminCursosNavegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminCursosNavegarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdminCursosNavegar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 90));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, 470));

        btnAgregarGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tips.png"))); // NOI18N
        btnAgregarGrupo.setText("Agregar grupo");
        btnAgregarGrupo.setBackground(new java.awt.Color(153, 255, 102));
        btnAgregarGrupo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAgregarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 170, 70));

        btnEliminarGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete.png"))); // NOI18N
        btnEliminarGrupo.setText("Eliminar grupo");
        btnEliminarGrupo.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminarGrupo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEliminarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 150, 70));

        btnEditarGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Help.png"))); // NOI18N
        btnEditarGrupo.setText("Editar grupo");
        btnEditarGrupo.setBackground(new java.awt.Color(255, 204, 102));
        btnEditarGrupo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditarGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 150, 70));

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Security_Firewall_OFF.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.setBackground(new java.awt.Color(204, 204, 204));
        btnCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 60));
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 490, -1));

        jLabel5.setText("Buscar:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, -1, 20));

        txtNombreGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 140, 30));

        jLabel7.setText("Nombre grupo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/noted_note_pen_notebook_write_icon_193919 (2).png"))); // NOI18N
        jLabel8.setText("Administrar Grupos");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarAsistenciasNavegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarAsistenciasNavegarActionPerformed
        this.dispose();
        new ConsultarAsistenciasFm(usuario).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarAsistenciasNavegarActionPerformed

    private void btnAdminCursosNavegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCursosNavegarActionPerformed
        this.dispose();
        new AdminCursoFm(usuario).setVisible(true);
    }//GEN-LAST:event_btnAdminCursosNavegarActionPerformed

    private void btnAdminGruposNavegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminGruposNavegarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminGruposNavegarActionPerformed

    private void btnImportAsistenciasNavegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportAsistenciasNavegarActionPerformed
        this.dispose();
        new ImportarAsistenciasFm(usuario).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImportAsistenciasNavegarActionPerformed

    private void cbxCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCursosActionPerformed
        this.cargarGrupos(false);
    }//GEN-LAST:event_cbxCursosActionPerformed

    private void btnAgregarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarGrupoActionPerformed
        Curso cursoSel = (Curso) cbxCursos.getSelectedItem();
//        grupos.agregar(new Grupo(cursoSel, txtNombreGrupo.getText(), java.sql.Date.valueOf(dateTimePickerFechaHoraInicio.getDatePicker().getDate())));
//        nuevos.add(new Grupo(cursoSel, txtNombreGrupo.getText(), java.sql.Date.valueOf(dateTimePickerFechaHoraInicio.getDatePicker().getDate())));
//        cargarGrupos(true);

        if (txtNombreGrupo.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Verifique que el nombre del grupo no esté vacío");
        } else if (dateTimePickerFechaHoraInicio.getDatePicker().getDate() == null) {
            
           JOptionPane.showMessageDialog(null, "Seleccione una fecha de inicio");
        } else {
             grupos.agregar(new Grupo(cursoSel, txtNombreGrupo.getText(), java.sql.Date.valueOf(dateTimePickerFechaHoraInicio.getDatePicker().getDate())));
            nuevos.add(new Grupo(cursoSel, txtNombreGrupo.getText(), java.sql.Date.valueOf(dateTimePickerFechaHoraInicio.getDatePicker().getDate())));
            cargarGrupos(true);
        }
    }//GEN-LAST:event_btnAgregarGrupoActionPerformed

    private void btnEditarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarGrupoActionPerformed
        if (seleccionado != null) {
            try {
                seleccionado.setCurso((Curso) cbxCursos.getSelectedItem());
                seleccionado.setNombre(txtNombreGrupo.getText());
                seleccionado.setFechaInicio(java.sql.Date.valueOf(dateTimePickerFechaHoraInicio.getDatePicker().getDate()));
                grupos.actualizar(seleccionado);
                nuevos.add(seleccionado);
            } catch (Exception e) {
                e.printStackTrace();
            }
            cargarGrupos(true);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un grupo para poder modificarlo");
        }
    }//GEN-LAST:event_btnEditarGrupoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int seleccionar = jTable1.rowAtPoint(evt.getPoint());
        Long id = (Long) (jTable1.getValueAt(seleccionar, 0));
        Grupo grupo = grupos.buscarPorId(id);
        this.seleccionado = grupo;
        txtNombreGrupo.setText(grupo.getNombre());
        cbxCursos.setSelectedItem(grupo.getCurso());
        Date fecha = this.addDays(grupo.getFechaInicio(), 1);
        if (!nuevos.isEmpty()) {
            if (nuevos.contains(grupo)) {
                fecha = grupo.getFechaInicio();
                grupo.setFechaInicio(fecha);
            }
        }
        dateTimePickerFechaHoraInicio.setDateTimeStrict(fecha.toLocalDate().atStartOfDay());
        cargarAlumnos();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnEliminarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarGrupoActionPerformed
        if (seleccionado != null) {
            try {
                grupos.eliminar(seleccionado.getId());
            } catch (Exception e) {
                e.printStackTrace();
            }
            cargarGrupos(false);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un grupo para poder eliminar");
        }
    }//GEN-LAST:event_btnEliminarGrupoActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int seleccionar = jTable2.rowAtPoint(evt.getPoint());
        Long id = (Long) (jTable2.getValueAt(seleccionar, 0));
        Alumno alumno = alumnos.buscarPorId(id);
        this.seleccionadoA = alumno;
        txtNombreAlumno.setText(alumno.getNombre());
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void txtNombreGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreGrupoActionPerformed

    private void btnAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlumnoActionPerformed
        if (seleccionado != null && !txtNombreAlumno.equals("")) {
            alumnos.agregar(new Alumno(txtNombreAlumno.getText(), seleccionado));
        } else {
            JOptionPane.showMessageDialog(null, "Verifique que haya seleccionado un grupo y que el nombre del alumno no está en blanco.");
        }
        cargarAlumnos();
    }//GEN-LAST:event_btnAgregarAlumnoActionPerformed

    private void btnEliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlumnoActionPerformed
        if (seleccionado != null && !txtNombreAlumno.equals("") && seleccionadoA != null) {
            alumnos.eliminar(seleccionadoA.getId());
        } else {
            JOptionPane.showMessageDialog(null, "Verifique que haya seleccionado un grupo y un alumno.");
        }
        cargarAlumnos();
    }//GEN-LAST:event_btnEliminarAlumnoActionPerformed

    private void btnEditarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAlumnoActionPerformed
        if (seleccionado != null && !txtNombreAlumno.equals("") && seleccionadoA != null) {
            seleccionadoA.setNombre(txtNombreAlumno.getText());
            seleccionadoA.setGrupo(seleccionado);
            alumnos.actualizar(seleccionadoA);
        } else {
            JOptionPane.showMessageDialog(null, "Verifique que haya seleccionado un grupo y un alumno.");
        }
        cargarAlumnos();
    }//GEN-LAST:event_btnEditarAlumnoActionPerformed

    private void cargarComboBoxCursos() {
        List<Curso> cursos = this.cursosDao.consultarCursos("", usuario.getId());
        cbxCursos.setModel(new DefaultComboBoxModel(cursos.toArray()));
    }

    private void cargarGrupos(boolean agregarEditar) {

        Curso cursoSel = (Curso) cbxCursos.getSelectedItem();
        List<Grupo> grupos = this.grupos.consultarGrupos(txtBuscar.getText(), cursoSel.getId());
        if (grupos != null) {
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);
            for (Grupo grupo : grupos) {
                Date fecha = this.addDays(grupo.getFechaInicio(), 1);
                grupo.setFechaInicio(fecha);
                if (!nuevos.isEmpty()) {
                    if (nuevos.contains(grupo)) {
                        fecha = this.subtractDays(grupo.getFechaInicio(), 1);
                        grupo.setFechaInicio(fecha);
                    }
                }
                modelo.addRow(grupo.toArray());
            }
        }
        this.grupos = new GrupoDAO();
    }

    private void cargarAlumnos() {
        List<Alumno> alumnos = this.alumnos.consultarAlumnos("", seleccionado.getId());
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        modelo.setRowCount(0);
        
        for (Alumno alumno : alumnos) {
            modelo.addRow(alumno.toArray());
        }
    }
    

    private Date addDays(Date date, int days) {
        Calendar c = Calendar.getInstance();
        c.setTime(date);
        c.add(Calendar.DATE, days);
        return new Date(c.getTimeInMillis());
    }

    private Date subtractDays(Date date, int days) {
        Calendar c = Calendar.getInstance();
        c.setTime(date);
        c.add(Calendar.DATE, -days);
        return new Date(c.getTimeInMillis());
    }

    public void centrarPantalla() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminCursosNavegar;
    private javax.swing.JButton btnAdminGruposNavegar;
    private javax.swing.JButton btnAgregarAlumno;
    private javax.swing.JButton btnAgregarGrupo;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConsultarAsistenciasNavegar;
    private javax.swing.JButton btnEditarAlumno;
    private javax.swing.JButton btnEditarGrupo;
    private javax.swing.JButton btnEliminarAlumno;
    private javax.swing.JButton btnEliminarGrupo;
    private javax.swing.JButton btnImportAsistenciasNavegar;
    private javax.swing.JComboBox<String> cbxCursos;
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePickerFechaHoraInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtNombreAlumno;
    private javax.swing.JTextField txtNombreGrupo;
    // End of variables declaration//GEN-END:variables
}
